[46.874284744] 2019-01-17 18:04:57,669 - INFO - launcher: Starting sanity checks
[46.874284744] 2019-01-17 18:04:57,669 - INFO - launcher: Checking for Python 3.5+
[46.874284744] 2019-01-17 18:04:57,669 - INFO - launcher: Checking console encoding
[46.874284744] 2019-01-17 18:04:57,669 - INFO - launcher: Setting console encoding to UTF-8
[46.874284744] 2019-01-17 18:04:57,669 - INFO - launcher: Ensuring we're in the right environment
[46.874284744] 2019-01-17 18:04:57,669 - INFO - launcher: Adding local bins/ folder to path
[631.719827652] 2019-01-17 18:04:58,253 - INFO - launcher: Required checks passed.
[678.627729416] 2019-01-17 18:04:58,300 - INFO - launcher: Optional checks passed.
[678.627729416] 2019-01-17 18:04:58,300 - INFO - launcher: Moving old musicbot log

######################### PRE-RUN SANITY CHECKS PASSED #########################

[1.4024991989135742] 2019-01-17 18:04:59,024 - WARNING - musicbot.config | In config.py::MainThread(15380), line 113 in run_checks: i18n file does not exist. Trying to fallback to config/i18n/en.json.
[1.4024991989135742] 2019-01-17 18:04:59,024 - INFO - musicbot.config | In config.py::MainThread(15380), line 124 in run_checks: Using i18n: config/i18n/en.json
[1.4024991989135742] 2019-01-17 18:04:59,024 - DEBUG - musicbot.json | In json.py::MainThread(15380), line 8 in __init__: Init JSON obj with config/i18n/en.json
[1.8556215763092041] 2019-01-17 18:04:59,477 - DEBUG - musicbot.bot | In bot.py::MainThread(15380), line 223 in _setup_logging: Set logging level to INFO
[1.8556215763092041] 2019-01-17 18:04:59,477 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 83 in __init__: Starting MusicBot 1.9.8_1
[1.8556215763092041] 2019-01-17 18:04:59,477 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 89 in __init__: Loaded autoplaylist with 3055 entries
[5.2816245555877686] 2019-01-17 18:05:02,903 - DEBUG - musicbot.bot | In bot.py::MainThread(15380), line 913 in on_ready: Connection established, ready to go.
[5.2816245555877686] 2019-01-17 18:05:02,903 - DEBUG - musicbot.bot | In bot.py::MainThread(15380), line 334 in _cache_app_info: Caching app info
[5.5672805309295654] 2019-01-17 18:05:03,189 - DEBUG - musicbot.bot | In bot.py::MainThread(15380), line 735 in _scheck_ensure_env: Ensuring data folders exist
[5.5672805309295654] 2019-01-17 18:05:03,189 - DEBUG - musicbot.bot | In bot.py::MainThread(15380), line 751 in _scheck_server_permissions: Checking server permissions
[5.5672805309295654] 2019-01-17 18:05:03,189 - DEBUG - musicbot.bot | In bot.py::MainThread(15380), line 755 in _scheck_autoplaylist: Auditing autoplaylist
[5.5672805309295654] 2019-01-17 18:05:03,189 - DEBUG - musicbot.bot | In bot.py::MainThread(15380), line 759 in _scheck_configs: Validating config
[5.5672805309295654] 2019-01-17 18:05:03,189 - DEBUG - musicbot.config | In config.py::MainThread(15380), line 213 in async_validate: Validating options...
[5.5672805309295654] 2019-01-17 18:05:03,189 - DEBUG - musicbot.bot | In bot.py::MainThread(15380), line 762 in _scheck_configs: Validating permissions config
[5.5672805309295654] 2019-01-17 18:05:03,189 - DEBUG - musicbot.permissions | In permissions.py::MainThread(15380), line 65 in async_validate: Validating permissions...
[5.5672805309295654] 2019-01-17 18:05:03,189 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 930 in on_ready: Connected: 533266784229523456/Test Music Bot#3711
[5.5672805309295654] 2019-01-17 18:05:03,189 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 938 in on_ready: Owner:     254851632481697792/Thunder#8077

[5.5672805309295654] 2019-01-17 18:05:03,189 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 941 in on_ready: Guild List:
[5.5672805309295654] 2019-01-17 18:05:03,189 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 944 in on_ready:  - ThunderServer
[5.5672805309295654] 2019-01-17 18:05:03,189 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 990 in on_ready: Not bound to any text channels
[5.5672805309295654] 2019-01-17 18:05:03,189 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 1003 in on_ready: Autojoining voice chanels:
[5.5672805309295654] 2019-01-17 18:05:03,189 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 1004 in <listcomp>:  - ThunderServer/Music Chill
[5.5672805309295654] 2019-01-17 18:05:03,189 - INFO - musicbot.bot | In bot.py::MainThread(15380), line 276 in _join_startup_channels: Attempting to join ThunderServer/Music Chill
